format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#D48668)\
$git_branch\
$git_status\
[](fg:#D48668 bg:#65889C)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$javascript\
$rust\
$scala\
[](fg:#65889C bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
[ ](fg:#33658A)\
[ ](fg:#fff)
"""
right_format = """
[](fg:#33658A)\
$time\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#fc1303"
format = '[ ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[python]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#D48668"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#D48668"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#65889C"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
use_12hr = true
style = "bg:#33658A"
format = '[  $time ]($style)'
