# This is the default configuration for a resetti profile.
# You can delete or ignore any sections which are not applicable.

[general]
# The type of reset style to use.
# Available options:
# - standard    Traditional single/multi-instance resetting for random seeds.
# - wall        Wall-style resetting for random seeds.
# - setseed     Set-seed resetter for good spawns, like spawn-juicer.
type = "wall"

# Whether or not to count the amount of resets performed.
count_resets = false

# The file to use for counting resets. This can be left blank
# if count_resets is disabled.
resets_file = ""

# The affinity setting to use. Does not apply when `advanced_wall.affinity` is
# enabled. Available options:
# - sequence    Set instances to run on every CPU       (0,   1,   2,   ..).
# - alternate   Set instances to run on every other CPU (0,   2,   4,   ..).
# - double      Set instances to run on 2 CPUs each     (0-1, 2-3, 4-5, ..).
mode = "double"

# Here, you can set various commands or shell scripts to run when certain
# events occur. Anything left blank will be ignored.
[hooks]
# The command/script to run when a reset from the wall occurs.
wall_reset = "paplay /home/pramodhsathya/Downloads/setups/media_reset.wav"

# The command/script to run when a reset occurs.
reset = "paplay /home/pramodhsathya/Downloads/setups/media_reset.wav"

# The command/script to run when an instance is locked on the wall.
lock = ""

# The command/script to run when an instance is unlocked on the wall.
unlock = ""

[obs]
# Whether or not to enable OBS websocket support. This is *required* for wall and setseed.
enabled = true

# The port to connect to OBS websocket on.
port = 4444

# The password to use when connecting. This can be left blank if you have
# authentication disabled in OBS websocket.
password = ""

[reset]
# The amount of milliseconds to wait before certain actions (e.g. stretching
# instance windows and clicking the mouse with `click_on_focus`.)
delay = 50

# Whether or not to automatically unpause the game when an instance is focused.
unpause_on_focus = true

# Whether or not to automatically click the mouse when focusing an instance.
# When disabled, you will have to click the mouse yourself. This is toggleable
# as the old behavior was to not click at all.
click_on_focus = true

# - You can ignore any keybindings here which do not apply to your reset style.
# - Alphanumerical and Fn keys (1-12) are supported.
# - If you'd like to use another key, use the syntax "code100" where 100 is the
#   keycode of the given key.
# - You can supply modifiers (Shift, Control, Alt) as well.
# - The values written are not case sensitive (e.g. `a` and `A` are equivalent,
#   specify the `Shift` modifier.)
# - There is no distinction between the left and right modifier keys.
# - For the wall keys, you may only specify modifiers. For example, if you specify
#   Shift as your wall instance reset keybind, pressing Shift-1 will reset the
#   first instance (if you have mouse support enabled, shift clicking will work
#   as well.) You can leave the keybind blank for no modifier.
# - Do not have multiple identical keybinds.
#
#   Examples:
#               `A` => The A key.
#               `a` => The A key.
#         `Shift-A` => The A key, only when Shift is held.
#  `Ctrl-Shift-F12` => The F12 key with Control and Shift held.
#         `code135` => The Menu key on my keyboard layout. Use xmodmap to find your desired key.
#
[keybinds]
# Pressing this will focus the current instance.
# If you on the wall, pressing this will send you back to the OBS projector.
focus = "Ctrl-Shift-F"

# Pressing this will reset the current instance.
# If you are on the wall, pressing this will reset all instances.
reset = "Ctrl-Shift-R"

# Pressing this will reset the selected instance.
wall_reset = "Ctrl-Shift"

# Pressing this will play the selected instance and reset all other instances.
wall_reset_others = "Shift"

# Pressing this will play the selected instance.
wall_play = "Ctrl"

# Pressing this will lock the selected instance.
wall_lock = "Alt"

[wall]
# Whether or not to stretch windows while on the wall for better visibility.
# Works with or without fullscreen.
stretch_windows = false

# The width to stretch windows to on the wall scene.
stretch_width = 1600

# The height to stretch windows to on the wall scene.
stretch_height = 300

# The width to unstretch windows to when being played.
unstretch_width = 1920

# The height to unstretch windows to when being played.
unstretch_height = 1080

# Whether or not to enable mouse support on the wall. Enabling this will allow
# you to click on instances to perform various actions instead of having to use
# the number keys. Note that enabling this does not disable the number keys.
use_mouse = false

# If enabled, resetting from within an instance will switch to the first locked
# instance (if any) instead of going back to the wall.
goto_locked = false

# More advanced wall settings, mainly aimed towards increasing performance.
[advanced_wall]
# Whether or not to use advanced affinity. All other affinity settings below
# only take effect if this is enabled. All affinity settings must be equal to
# or less than the number of CPU threads you have.
affinity = true

# Number of CPUs to run idle instances on.
affinity_idle = 1

# Number of CPUs to run low priority instances on.
affinity_low = 4

# Number of CPUs to run high priority instances on.
affinity_high = 6

# Number of CPUs to run the actively played instance on.
affinity_active = 8

# The world generation percentage to reach before moving an instance
# from high priority to low priority.
low_threshold = 20

# Whether or not to freeze instances after they have been idle for some time.
# NOTE: DO NOT enable this with the OpenAL PulseAudio backend. You will likely
# experience increased CPU utilization on all of your instances. Switch to
# the `pipewire` driver if possible or do not use this setting.
freeze_idle = false

# The delay in milliseconds before freezing an instance after it has finished
# generating.
freeze_delay = 1000

# The maximum number of instances which can reset at the same time. Set to 0 to
# disable. Requires instance freezing to be enabled.
max_concurrent_resets = 0

# You can delete this section or leave it as is if you are not using the
# set-seed resetter.
[setseed]
# The seed to use.
seed = "my_seed"

# The desired spawn X and Z coordinates.
spawn_x = 123.0
spawn_z = 456.0

# The radius around the given X/Z coordinates which is considered "good."
radius = 5.0
