reset_count = '/home/pramodhsathya/reset_count.txt'
unpause_focus = true
poll_rate = 100
play_res = '1920x1080+0,0'
alt_res = ['220x700+860,190', '1920x300+0,390', '320x16384+800,-7652']
disable_pause = false
utility_mode = false

[delay]
wp_pause = 20
idle_pause = 20
unpause = 50
stretch = 50
ghost_pie_fix = 20

[hooks]
reset = 'sh /home/pramodhsathya/wall.sh'
alt_res = ['sh /home/pramodhsathya/thin.sh', 'sh /home/pramodhsathya/wide.sh', 'sh /home/pramodhsathya/tall.sh']
normal_res = ['sh /home/pramodhsathya/reset.sh', 'sh /home/pramodhsathya/reset.sh', 'sh /home/pramodhsathya/tall_reset.sh']
wall_lock = ''
wall_unlock = ''
wall_play = ''
wall_reset = ''

[keybinds]
R = ['wall_reset_all']
grave = ['ingame_toggle_res(1)']
Ctrl-Shift-F = ['ingame_focus', 'wall_focus']
LMB = ['wall_reset']
LMB-Ctrl = ['wall_play']
LMB-Alt = ['wall_lock']
RMB = ['wall_lock']
LMB-Ctrl-Shift = ['wall_reset_others']
Z = ['ingame_reset']
Q = ['wall_play_first_locked']
2 = ['wall_reset(1)']
Ctrl-2 = ['wall_play(1)']
6 = ['ingame_toggle_res(2)']
J = ['ingame_toggle_res(3)']

[obs]
enabled = true
port = 4444
password = ''
port_2 = 4444
password_2 = ''

[wall]
enabled = true
confine_pointer = false
goto_locked = true
reset_unlock = true
grace_period = 5000
stretch_res = '1920x1080+-1919,1079'
use_f1 = false
freeze_at = 90
show_at = -1
wall_window = 'Projector (Scene) - Wall'

[wall.moving]
enabled = true
use_gaps = true
force_reset_before_play = false

[[wall.moving.groups]]
position = '1368x882+276,101'
cosmetic = false
width = 3
height = 2

[[wall.moving.groups]]
position = '93x882+166,101'
cosmetic = true
width = 1
height = 4

[wall.moving.locks]
position = '1368x101+276,0'
width = 4
height = 1

[wall.performance]
sleepbg_path = ''
affinity = 'advanced'

[wall.performance.sequence]
active_cpus = 6
background_cpus = 4
lock_cpus = 8

[wall.performance.advanced]
ccx_split = 1
affinity_idle = 1
affinity_low = 2
affinity_mid = 4
affinity_high = 6
affinity_active = 8
burst_length = 500
low_threshold = 30
