reset_count = ''
unpause_focus = true
poll_rate = 100
play_res = '1920x1080+0,0'
alt_res = '1920x300+0,390'

[delay]
wp_pause = 20
idle_pause = 20
unpause = 20
stretch = 20
ghost_pie_fix = 20
warp = 0

[hooks]
reset = ''
alt_res = ''
normal_res = ''
wall_lock = ''
wall_unlock = ''
wall_play = ''
wall_reset = ''

[keybinds]
Ctrl-Shift-D = ['wall_reset_all', 'ingame_reset']
Ctrl-Shift-F = ['ingame_focus', 'wall_focus']
LMB = ['wall_reset']
LMB-Shift = ['wall_play']
LMB-Ctrl = ['wall_lock']
LMB-Ctrl-Shift = ['wall_reset_others']
1 = ['wall_reset(1)']
Shift-1 = ['wall_play(1)']
6 = ['ingame_toggle_res']

[obs]
enabled = false
port = 4440
password = ''
port_2 = 4441
password_2 = ''

[wall]
enabled = false
confine_pointer = false
goto_locked = false
reset_unlock = false
grace_period = 250
stretch_res = '960x360+0,0'
use_f1 = false
freeze_at = 0
show_at = 5
wall_window = 'Projector (Scene) - Wall'

[wall.moving]
enabled = false
force_reset_before_play = false
use_gaps = true

[[wall.moving.groups]]
position = '1920x880+0,0'
cosmetic = false
width = 2
height = 2

[wall.moving.locks]
position = '1920x200+0,880'
cosmetic = false
width = 6
height = 1

[wall.performance]
sleepbg_path = ''
affinity = ''

[wall.performance.sequence]
active_cpus = 12
background_cpus = 8
lock_cpus = 10

[wall.performance.advanced]
ccx_split = 1
affinity_idle = 2
affinity_low = 4
affinity_mid = 8
affinity_high = 12
affinity_active = 12
burst_length = 0
low_threshold = 20
