# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				egg = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				hoglin = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				item_frame = true
				horse = true
				minecart = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				villager = true
				fishing_bobber = true
				zombie_villager = true
				strider = true
				painting = true
				cod = true
				witch = true
				snow_golem = true
				spider = true

